# Generated by Django 6.0.2 on 2026-09-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_pendingsignup_code_pendingsignup_code_attempts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RateLimitAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(max_length=64)),
                ('client_ip', models.CharField(max_length=45)),
                ('count', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField(db_index=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('scope', 'client_ip'), name='unique_ratelimit_scope_ip')],
            },
        ),
    ]
