# Generated by Django 6.0.2 on 2026-09-09 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subtask',
            options={'ordering': ['-dateCreated']},
        ),
    ]
