# Generated by Django 6.0.2 on 2026-09-11 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_subtask_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('dateCreated', models.DateTimeField(auto_now_add=True)),
                ('dateStart', models.DateTimeField()),
                ('dateEnd', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['dateStart'],
                'indexes': [models.Index(fields=['user', 'dateStart'], name='tasks_calen_user_id_1f05ac_idx')],
            },
        ),
    ]
