"""
Django settings for flexmaster project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
from django.urls import reverse_lazy
from celery.schedules import crontab
import os
from dotenv import load_dotenv
import flexmaster

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

load_dotenv()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")
# Render (and most similar platforms) inject this automatically on
# every service, with the actual public *.onrender.com hostname — so
# a Render deploy never needs ALLOWED_HOSTS set by hand at all.
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# --- Error monitoring (Sentry) ---
# Without this, an unhandled exception in production is silent — it
# just 500s for whoever hit it, and nobody finds out unless that
# person happens to report it. Free tier (5k events/month), no cost.
# Only initializes when SENTRY_DSN is actually set, so this is a no-op
# everywhere it isn't deliberately configured (local dev, CI, this
# repo's test suite) — nothing new to install/run, nothing sent
# anywhere, same as every other env-var-gated optional integration in
# this file (DIGEST_CRON_TOKEN, CELERY_BROKER_URL).
SENTRY_DSN = os.getenv("SENTRY_DSN")
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        integrations=[DjangoIntegration()],
        # Performance-trace sampling, separate from error capture (which
        # is always on) — 10% keeps the free tier's transaction quota
        # from being eaten by every single request under even modest
        # traffic, while still surfacing genuinely slow endpoints.
        traces_sample_rate=0.1,
        environment="production" if not DEBUG else "development",
        # Opt-out by default: only the error itself gets sent, not
        # request/user data (cookies, IPs, form bodies, session
        # contents) to this third party. Turn on deliberately later if
        # actually needed for debugging, rather than leaking it by
        # default from day one.
        send_default_pii=False,
    )

# Historical note, not the current deployment: this app used to run as
# two separate Render services (fauxcus-frontend and fauxcus-api), each
# on its own onrender.com subdomain — which makes every session/CSRF
# cookie "cross-site" from the browser's point of view. Django's
# default SameSite=Lax cookie is invisible to a fetch() call from
# another origin — only top-level navigation gets it — so login would
# silently appear to work (200 OK) but never actually authenticate
# anything after it. Fixed properly by folding the frontend into this
# same service instead (see render.yaml) rather than by this setting —
# same-origin requests don't need SameSite=None at all. Left in place
# because it's harmless for same-origin traffic and keeps this correct
# if the two ever split apart again (a different host, a staging
# frontend on its own subdomain, etc). SameSite=None itself requires
# Secure (HTTPS-only) alongside it, which is why this only flips when
# DEBUG is off — local dev talks over plain http://localhost, where a
# Secure-only cookie would never be sent at all. SECURE_PROXY_SSL_HEADER
# tells Django to trust the X-Forwarded-Proto header these platforms
# set at their edge, since the app itself is reached over plain HTTP
# inside their network — without it, request.is_secure() reads False
# even in production and the two Secure cookies above never actually
# get set.
SESSION_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Baseline: no persistent login cookie unless something explicitly asks
# for one. Without this, Django's default is a session that survives
# closing the browser entirely (governed by SESSION_COOKIE_AGE below,
# 2 weeks out of the box) for *every* login, with no way to opt out —
# too long a window to leave logged in by default on, say, a shared
# computer. user.api_views.login_api is the one place that opts back
# in (via request.session.set_expiry(SESSION_COOKIE_AGE)) when its
# "remember me" checkbox was checked; every other place a session gets
# established (signup, password reset) just inherits this same
# session-ends-at-browser-close default.
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
# How long "remember me" actually remembers — only takes effect where
# login_api explicitly opts in above; Django's own default (2 weeks).
SESSION_COOKIE_AGE = 1209600

# Application definition

INSTALLED_APPS = [
    'user',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.sites',

    #ALL_AUTH
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',

    #my apps
    'pages',
    'tasks',
    'django_filters',
    'corsheaders',
    'rest_framework',

]

#SITE_ID = 1

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves the built frontend (see WHITENOISE_ROOT below) directly out
    # of this same process on Render — must sit early, before anything
    # that assumes every request is an API call. A no-op locally: local
    # dev never has frontend/dist (the Vite dev server on :3000 handles
    # the frontend there instead), so WhiteNoise just finds nothing to
    # serve and every request falls through to Django's normal routing
    # exactly as before.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #ALL_AUTH
    #'allauth.account.middleware.AccountMiddleware',

    #my_middleware
    #"tasks.middleware.TimezoneMiddleware",
]

ROOT_URLCONF = 'flexmaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flexmaster.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Render (like most PaaS databases) hands over one DATABASE_URL
# connection string rather than the five discrete pieces docker-compose
# sets — parsed here with dj-database-url rather than five more
# fromDatabase env vars in render.yaml, whose exact property names
# (host/port specifically) aren't documented as available outside a
# Render *service* reference. Local dev never sets DATABASE_URL, so
# this falls through to the existing discrete-vars config unchanged.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    import dj_database_url

    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# The built React app (Dockerfile.render's frontend-build stage output)
# — WhiteNoise serves whatever's in here directly at the URL root
# (index.html's own referenced /assets/*.js, /icon-a-512.png, etc.),
# independently of STATIC_URL/STATICFILES_DIRS/collectstatic above,
# which stay exactly as they were for Django's own static files.
# Doesn't exist in local dev (frontend/dist is gitignored and never
# built into the plain local Dockerfile) — WhiteNoise just no-ops if
# the directory itself is missing, so this is safe to leave unguarded.
WHITENOISE_ROOT = BASE_DIR.parent / "frontend" / "dist"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'user.authentication.EmailOrUsernameBackend',
    #"allauth.account.auth_backends.AuthenticationBackend",
]

# SOCIALACCOUNT_PROVIDERS = {}
#

# Use 'django.core.mail.backends.smtp.EmailBackend' for live emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'                # e.g., smtp.gmail.com or smtp.sendgrid.net
EMAIL_PORT = 587                             # 587 is standard for TLS
EMAIL_USE_TLS = True                         # Use Transport Layer Security
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# The address itself has to stay this real Gmail account (EMAIL_HOST_USER,
# above) — Gmail's SMTP relay silently discards a From header whose address
# isn't the authenticated account or a verified "Send As" alias on it, and
# falls back to that account's own default sender identity. Every send_mail()
# call must use this constant (not a made-up 'noreply@...' string) so the
# display name actually shows "Fauxcus" instead of the account owner's name.
# To send from a real Fauxcus-owned address instead of this personal Gmail,
# either add that address as a verified alias in this Gmail account's "Send
# mail as" settings, or switch EMAIL_BACKEND to a transactional provider
# (SendGrid/Mailgun/SES/etc.) with its own verified sending domain.
DEFAULT_FROM_EMAIL = 'Fauxcus <pantheraleo440@gmail.com>'

# Shared secret for tasks.api.views.TriggerDeadlineDigestView — lets a
# free GitHub Actions `schedule:` cron (.github/workflows/deadline-digest-cron.yml)
# trigger `send_deadline_digest` in production over plain HTTP, since
# Render's free tier has no Worker/Cron Job to run a persistent process
# there at all (see render.yaml's own comments). Must match the
# DIGEST_CRON_TOKEN secret set on that workflow. Unset (None/"") locally,
# which the view treats as "digest-triggering disabled" rather than
# "any token matches".
DIGEST_CRON_TOKEN = os.getenv('DIGEST_CRON_TOKEN')

# --- Celery (backend/flexmaster/celery.py) ---
# Local-dev-only — see that file's docstring for why this never runs in
# production. Runs the exact same send_deadline_digest command
# DIGEST_CRON_TOKEN's endpoint calls directly for prod, just via Celery
# Beat locally instead of docker-compose.yml's old `scheduler` service.
CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_BEAT_SCHEDULE = {
    'send-deadline-digest-daily': {
        'task': 'tasks.tasks.send_deadline_digest_task',
        # Same UTC hour backend/scheduler.py used to default to
        # (DIGEST_HOUR_UTC), and the same hour the GitHub Actions
        # digest cron uses for production — all three agree on "when".
        'schedule': crontab(hour=int(os.getenv('DIGEST_HOUR_UTC', '13')), minute=0),
    },
}
#
# ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('user_profile')
LOGOUT_REDIRECT_URL = '/'

# ACCOUNT_SIGNUP_REDIRECT_URL = reverse_lazy('user_profile')
# Google client ID: 49082574881-obouglaf93ocirrqs4d7eh5udjdo7i18.apps.googleusercontent.com

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Where the React app lives — needed because the multi-step signup flow's
# verification email links to a React route (/signup/verify/<token>/),
# not a Django-rendered page, so this server has to know that origin
# instead of assuming its own (unlike the old activation email, which
# links to itself). Also doubles as the deployed frontend's real origin
# for CORS/CSRF below.
#
# On Render this is now the same origin as this API itself (the built
# frontend is served straight out of this process — see
# WHITENOISE_ROOT below and Dockerfile.render), so it defaults to
# RENDER_EXTERNAL_HOSTNAME when present rather than needing to be set
# by hand — the two are never actually different values there anymore.
# An explicit FRONTEND_URL still overrides this (e.g. a custom domain
# later, or if the frontend ever moves to its own service again).
_render_host_for_frontend = os.getenv("RENDER_EXTERNAL_HOSTNAME")
FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    f"https://{_render_host_for_frontend}" if _render_host_for_frontend else "http://localhost:3000",
)

# ADDITIONAL_TRUSTED_ORIGINS covers any other origin that needs to talk to
# this API — a custom domain alongside the platform's own subdomain, or a
# host (like Vercel) that gives every preview deploy its own random
# subdomain FRONTEND_URL alone can't predict. Comma-separated, e.g.
# "https://fauxcus.com,https://fauxcus-git-my-branch.vercel.app".
_extra_origins = [o.strip() for o in os.getenv("ADDITIONAL_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# The local dev server's origin stays trusted unconditionally — a
# deployed FRONTEND_URL replacing it here would otherwise break local
# development against a prod-configured .env.
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(["http://localhost:3000", FRONTEND_URL, *_extra_origins]))
CORS_ALLOW_CREDENTIALS = True

# Required for a cross-origin frontend to make authenticated
# POST/PATCH/DELETE requests against this API — Django's CSRF middleware
# rejects cross-origin unsafe requests unless the origin is explicitly
# trusted here, separately from CORS.
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(["http://localhost:3000", FRONTEND_URL, *_extra_origins]))