"""
Django settings for flexmaster project.

Generated by 'django-admin startproject' using Django 4.2.18.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os.path
from pathlib import Path
from django.urls import reverse_lazy
import os
from dotenv import load_dotenv
import flexmaster

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

load_dotenv()
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False") == "True"
ALLOWED_HOSTS = os.getenv("ALLOWED_HOSTS", "localhost").split(",")
# Render (and most similar platforms) inject this automatically on
# every service, with the actual public *.onrender.com hostname — so
# a Render deploy never needs ALLOWED_HOSTS set by hand at all.
_render_host = os.getenv("RENDER_EXTERNAL_HOSTNAME")
if _render_host:
    ALLOWED_HOSTS.append(_render_host)

# A real deployment puts the frontend and this API on two different
# domains — two separate Render services here (fauxcus-frontend and
# fauxcus-api), each on its own onrender.com subdomain — which makes
# every session/CSRF cookie "cross-site" from the browser's point of
# view. Django's default SameSite=Lax cookie is invisible to a fetch()
# call from another origin — only top-level navigation gets it — so
# login would silently appear to work (200 OK) but never actually
# authenticate anything after it. SameSite=None fixes that, but the
# spec requires Secure (HTTPS-only) alongside it, which is why this
# only flips when DEBUG is off — local dev talks over plain
# http://localhost, where a Secure-only cookie would never be sent at
# all. SECURE_PROXY_SSL_HEADER tells Django to trust the
# X-Forwarded-Proto header these platforms set at their edge, since the
# app itself is reached over plain HTTP inside their network — without
# it, request.is_secure() reads False even in production and the two
# Secure cookies above never actually get set.
SESSION_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SAMESITE = "Lax" if DEBUG else "None"
CSRF_COOKIE_SECURE = not DEBUG
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# Application definition

INSTALLED_APPS = [
    'user',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #'django.contrib.sites',

    #ALL_AUTH
    # 'allauth',
    # 'allauth.account',
    # 'allauth.socialaccount',
    # 'allauth.socialaccount.providers.google',

    #my apps
    'pages',
    'tasks',
    'django_filters',
    'corsheaders',
    'rest_framework',

]

#SITE_ID = 1

AUTH_USER_MODEL = 'user.CustomUser'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    #ALL_AUTH
    #'allauth.account.middleware.AccountMiddleware',

    #my_middleware
    #"tasks.middleware.TimezoneMiddleware",
]

ROOT_URLCONF = 'flexmaster.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'flexmaster.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
#
# Render (like most PaaS databases) hands over one DATABASE_URL
# connection string rather than the five discrete pieces docker-compose
# sets — parsed here with dj-database-url rather than five more
# fromDatabase env vars in render.yaml, whose exact property names
# (host/port specifically) aren't documented as available outside a
# Render *service* reference. Local dev never sets DATABASE_URL, so
# this falls through to the existing discrete-vars config unchanged.
_database_url = os.getenv("DATABASE_URL")
if _database_url:
    import dj_database_url

    DATABASES = {"default": dj_database_url.parse(_database_url, conn_max_age=600)}
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": os.getenv("POSTGRES_DB"),
            "USER": os.getenv("POSTGRES_USER"),
            "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
            "HOST": os.getenv("POSTGRES_HOST"),
            "PORT": os.getenv("POSTGRES_PORT"),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'user.authentication.EmailOrUsernameBackend',
    #"allauth.account.auth_backends.AuthenticationBackend",
]

# SOCIALACCOUNT_PROVIDERS = {}
#

# Use 'django.core.mail.backends.smtp.EmailBackend' for live emails
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'                # e.g., smtp.gmail.com or smtp.sendgrid.net
EMAIL_PORT = 587                             # 587 is standard for TLS
EMAIL_USE_TLS = True                         # Use Transport Layer Security
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
# The address itself has to stay this real Gmail account (EMAIL_HOST_USER,
# above) — Gmail's SMTP relay silently discards a From header whose address
# isn't the authenticated account or a verified "Send As" alias on it, and
# falls back to that account's own default sender identity. Every send_mail()
# call must use this constant (not a made-up 'noreply@...' string) so the
# display name actually shows "Fauxcus" instead of the account owner's name.
# To send from a real Fauxcus-owned address instead of this personal Gmail,
# either add that address as a verified alias in this Gmail account's "Send
# mail as" settings, or switch EMAIL_BACKEND to a transactional provider
# (SendGrid/Mailgun/SES/etc.) with its own verified sending domain.
DEFAULT_FROM_EMAIL = 'Fauxcus <pantheraleo440@gmail.com>'
#
# ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']

LOGIN_URL = reverse_lazy('login')
LOGIN_REDIRECT_URL = reverse_lazy('user_profile')
LOGOUT_REDIRECT_URL = '/'

# ACCOUNT_SIGNUP_REDIRECT_URL = reverse_lazy('user_profile')
# Google client ID: 49082574881-obouglaf93ocirrqs4d7eh5udjdo7i18.apps.googleusercontent.com

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

# Where the React app lives — needed because the multi-step signup flow's
# verification email links to a React route (/signup/verify/<token>/),
# not a Django-rendered page, so this server has to know that origin
# instead of assuming its own (unlike the old activation email, which
# links to itself). Also doubles as the deployed frontend's real origin
# for CORS/CSRF below, so pointing this at e.g. a Vercel domain is the
# only env change a real deployment needs for the two — no code change.
FRONTEND_URL = os.getenv("FRONTEND_URL", "http://localhost:3000")

# ADDITIONAL_TRUSTED_ORIGINS covers any other origin that needs to talk to
# this API — a custom domain alongside the platform's own subdomain, or a
# host (like Vercel) that gives every preview deploy its own random
# subdomain FRONTEND_URL alone can't predict. Comma-separated, e.g.
# "https://fauxcus.com,https://fauxcus-git-my-branch.vercel.app".
_extra_origins = [o.strip() for o in os.getenv("ADDITIONAL_TRUSTED_ORIGINS", "").split(",") if o.strip()]

# The local dev server's origin stays trusted unconditionally — a
# deployed FRONTEND_URL replacing it here would otherwise break local
# development against a prod-configured .env.
CORS_ALLOWED_ORIGINS = list(dict.fromkeys(["http://localhost:3000", FRONTEND_URL, *_extra_origins]))
CORS_ALLOW_CREDENTIALS = True

# Required for a cross-origin frontend to make authenticated
# POST/PATCH/DELETE requests against this API — Django's CSRF middleware
# rejects cross-origin unsafe requests unless the origin is explicitly
# trusted here, separately from CORS.
CSRF_TRUSTED_ORIGINS = list(dict.fromkeys(["http://localhost:3000", FRONTEND_URL, *_extra_origins]))